version: '3.8'

services:
  api-jarspeed:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongodb
    environment:
      MYSQL_URL: jdbc:mysql://db:3306/jarspeed?useSSL=false&allowPublicKeyRetrieval=true
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: user
      MONGODB_URI: mongodb://mongoadmin:mongopassword@mongodb:27017/jarspeed?authSource=admin
    networks:
      - jarspeed-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'jarspeed'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    networks:
      - jarspeed-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - jarspeed-network

volumes:
  db_data:
  mongodb_data:

networks:
  jarspeed-network:

